### PR TITLE
manual or auto download of attachments

### PR DESCRIPTION
**Pull request by ron282**

### CODE REVIEW

**Comment by geobra** [comment]
Have to build and test this on my device...

**Comment by geobra** [comment]
Short update. My mainboard died :-(. Ordered a new one. Stay tuned...

**Comment by geobra** [comment]
My setup is working again :-). Just did a review, build and tested it. Looks good to me. Ready to merge or do you want to adapt anything further?

**Comment by ron282** [comment]
Good to know you're back! I have additional changes: regarding ui improvements, omemo and muc. It's better to merge current changes and then I will create new pull requests for these additional changes ;)

**Pull request merged**
