### PR TITLE
replaced image picker with Silica image picker

### PR DESCRIPTION
**Pull request by slohse**
This PR removes ImagePickerPage and FileModel and replaces it with the native Silica ImagePicker. This has the advantage that not only images under `/home/nemo/Pictures` can be picked, but also images in the `Pictures` folder on the SD card. This is convenient for users who configured their camera app to store images on the SD card.

I hope I did not forget anything when cleaning now unused remnants...

### CODE REVIEW

**Comment by geobra** [comment]
Hi

I also thought about using the now available Silica ImagePicker instead of the current implementation. That makes the code smaller and more clear. On the other side it reduces some functionality. Current implementation scans the complete home directory (QStandardPaths::HomeLocation) for images. On my device, this takes several seconds. But it gets you all the pictures (even from other messangers or apps) displayed by creation time. 

Is there a way to configure additional pathes where the Silica ImagePicker should scan for images?

**Comment by slohse** [comment]
Unfortunately neither the [ImagePickerPage](https://sailfishos.org/develop/docs/sailfish-components-pickers/qml-sailfish-pickers-imagepickerpage.html/) nor the [MultiImagePickerDialog](https://sailfishos.org/develop/docs/sailfish-components-pickers/qml-sailfish-pickers-multiimagepickerdialog.html/) have a (documented) way to set the folder(s) to take into account.

On the other hand I could also not find a way to get the path to the SD card, which is mounted under `/media/sdcard/<UUID>`, which obviously differs on every device. I found [this exchange from 2014 on the mailing list](https://lists.sailfishos.org/pipermail/devel/2014-January/003150.html), but as that answer implies, the `/run/user/100000/media/sdcard` path is gone, yet I cannot find any documentation on "middleware to handle SD-card related functionality (informing if
SD-card is present, and at which path, notify about removal, ...)".

**Comment by slohse** [comment]
(because that was my first idea - modify the FileModel to accept multiple paths and add the Pictures folder on the SD card to the paths used)

**Comment by geobra** [comment]
Personally, I created a simlink from my ~/Pictures folder to the sd card with the pictures. This method will work for every location. But of course need's manual setup and is not end-user friendly. The simlink approach can also be used with the Silica ImagePicker. I am not sure which implementation is best for future use...

**Comment by geobra** [comment]
The sdcard is always mounted to /media/sdcard/<UUID>. So one could read the /media/sdcard folder and user whatever uuid follows. But then again, the Picture location on sd-card is unkonwn.

Another approach could be to make additional Picture Locations selectable by the user. This locations can than be passed to the Filemodel class.

**Comment by slohse** [comment]
I was hoping I'd find the time this weekend to implement the alternative - modify FileModel to accept multiple paths. Didn't manage, maybe some other time this week.

The Symlink is a good idea, but as you say, needs (non-obvious) user action. I wonder what happens if you do symlink from `/home/nemo/Pictures` to `/home/nemo` with the Silica ImagePicker - will all Pictures in `/home/nemo/Pictures/` show up twice?

I like the "make it user configurable" approach, but that requires some more work around it (creating a settings UI and so on).

**Comment by slohse** [comment]
closing in favour of #30

**Pull request closed without merging**
