### PR TITLE
Alternative to PR #27, make ImagePicker/FileModel configurable

### PR DESCRIPTION
**Pull request by slohse**
Work-in-Progress Pull Request as a proposed alternative to PR #27
In this one we keep the image picker, but modify it to accept multiple search paths. This gives us the option to make it user-configurable (which needs to be implemented still)

I verified that it works by testing it with `[StandardPaths.home]` (as it is in the PR now),  `[StandardPaths.videos]`, `[StandardPaths.pictures]` and `[StandardPaths.videos, StandardPaths.pictures]`

Feel free to discuss and/or add commits

### CODE REVIEW

**Comment by geobra** [comment]
Good concept. I think this is the way we should go.
Unfortunately the imagePicker is the only 'ready to use' silicia picker until now. We need something like an directory picker for the UI part. 
Let's have a look on other projects, if there is something usable around...

**Comment by slohse** [comment]
Moved all (Q)Settings to a separate class. I then added the section `storage` to the settings file and the key `imagePaths` which can contain a list of paths, for example:
```
[storage]
imagePaths=/home/nemo/Pictures, /home/nemo/Videos, /home/nemo/Music
```

The Image selector now uses this setting. In absence of this setting, `QStandardPaths::PicturesLocation` is used.

Still missing UI to configure this list, though.

**Comment by carlosgonzz** [comment]
any progress of this slohse?

**Comment by slohse** [comment]
No, I haven't had time, sadly.
I have some more uncommitted, presumably non-working (I don't remember) changes here...

**Comment by GNUuser** [comment]
ok thanks. i would like if you can push this PR :  )

**Comment by geobra** [comment]
Me too :-)

**Comment by slohse** [comment]
I'll see if I can make some room for that. No promises, though :)

**Comment by slohse** [comment]
looks roughly like this

**Comment by geobra** [comment]
Really nice work! Thank you for this :-).

**Comment by GNUuser** [comment]
thanks @slohse.

**Pull request merged**
