### PR TITLE
Enable landscape orientation on all pages.

### PR DESCRIPTION
**Pull request by mazhe**
Hi,

It would be nice to have landscape mode for shmoose, do you think this would be ok? If you would think this may not be desirable for everybody, it seems feasible to subject this to a setting, but this does not seems to be something application usually propose.

Thanks!

### CODE REVIEW

**Comment by mazhe** [comment]
Just a comment: only the MenuPage is a bit off due to the (empty?) avatar image that push the menu a bit too far and require some scrolling that appears to be uneeded... If the empty image is by design some kind of spacer, it is possible do only enable it in portrait mode.

**Comment by geobra** [comment]
Looks good on my test device, also in landscape mode. The (hidden) avatar on the menu page was planed to show the own avatar image sometimes in the future. We could show a dummy now or remove it complete until there is a good implementation for this. You decide ;-).

**Comment by geobra** [comment]
If you don't want to adjust something here, I can also accept this PR and do the little adaption by myself if you prefer...

**Comment by mazhe** [comment]
Yes, sorry, I had looked for a "default" avatar thingy in sailfish doc with no avail then got occupied with other events. Actually I'm OK with things as they are : I realized even with this spacing, there's even no need to scroll in the MenuPage.

Let's go with this!

**Pull request merged**
