### PR TITLE
Video, Audio, File attachments, upload progress, save msg before sending attachment

### PR DESCRIPTION
**Pull request by ron282**
Hi ,

I did few changes :)
- Manage any type of attachment
- Play video and audio attachment (needs to be improved, this is very basic)
- Save msg before end of upload of attachment to improve responsiveness
- Nicer display of timestamps
- Show progress of upload of attachment

But I have few issues:
- For preview of image, video and audio, I'm using the Thumbnail control and sometimes when receiving a signal, all the previews disappear. I need to toggle with another application to bring them back
- When showing the status of the message, sometimes it is not updated.

### CODE REVIEW

**Comment by geobra** [comment]
A lot of features. Thank you :-).
I am currently in vacation and have only limited display space available ;-). Will review it in about two weeks when I am back at home.

**Comment by ron282** [comment]
Thanks for your feedback. I need also some advises for next steps. I'm looking at improving mam to support OMEMO fro instance but this is not easy. Enjoy your vacations.

**Comment by ron282** [comment]
I need to fix some late issues I found

**Comment by geobra** [comment]
Just did a fresh build and run it on my device. I really like the new features :-)!

But I also did some functional testing and some things are not as stable as it should be:
- Sometimes the picture or video does not get send at all. It is stuck with no indicator or progress update.
- On my device is a UI glitch if I touch on the preview
- Turning omemo on/off for sending files also disables sending of files on my device

I will do a code review later this week and try to figure out what is going on. We have to address this issues to get it work smoothly...

**Comment by ron282** [comment]
Regarding the pictures or video not sent at all, I need to dig. This is likely due to  a lack of error management. There is the same issue with download.

Regarding omemo on/off disable sending files, I don't reproduce it.

**Comment by ron282** [comment]
I added the management of errors for uploads, I will push it this week-end but I'm thinking about about improvements

**Pull request closed without merging**
