### PR TITLE
Message Carbons (XEP-0280)

### LINKED ISSUE #34: If Gajim and Shmoose are open at the same time, the messages are not delivered to Shmoose

### PR DESCRIPTION
**Pull request by rogora**
I implemented message carbons. I'm testing this successfully with my build of Shmoose that uses Swiften 4, but it might work also on Swiften 3.

Fixes #34

### CODE REVIEW

**Comment by rogora** [comment]
I'm sorry, I'm really bad with github. Anyways, I'm proposing three different things:
- message carbons
- fix the http image upload (GET and PUT are swapped)
- do not discard group messages without ids (I had to add this change because I was not receiving group messages from my Prosody server with Spectrum2 transports)

**Comment by geobra** [comment]
Thank you for this. Message Carbons are new to me from an implementation point of view. Will have a look at it the next days.

**Comment by geobra** [comment]
Does not compile with Swiften 3 here. So I suggest to wait with this pull request until Swift 4 is compileable with the mainline sfos compiler.

**Comment by geobra** [comment]
@rogora 
Finnaly SFOS has updated gcc to version 8. I just tested the early access SDK with swiften 4.0.2 and it seems to work well. Could you update your pull request to address the latest project changes?

**Comment by rogora** [comment]
Finally a decent gcc version! :)
I see that you're actively working on the project these days, let me know when things are stable enough to rebase my pull request.

**Comment by geobra** [comment]
Okay, I will ping you as soon as the EA SDK is official released and shmoose builds sucessfull against this.

**Comment by GNUuser** [comment]
New SDK is out: https://sailfishos.org/wiki/Application_SDK#Latest_SDK_Release

**Comment by geobra** [comment]
I have tested the final SDK version today. Build against swiften 4 succeeds. Tests are running fine and the app is running on my development phone without issues right now. The source code should now be stable enough to receive pull requests ;-)

**Pull request closed without merging**
